services:
  telemons-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: telemons-app-dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    command: sh -c "npx prisma generate && npm run dev"

  redis:
    image: redis:7-alpine
    container_name: telemons-redis
    ports:
      - "6379:6379"
    restart: unless-stopped   